import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import axios, { AxiosError } from 'axios';

type Datatype = {
  accessibility: Number,
  activity: String,
  participants: Number,
  type: String,
  price: Number,
  link: String
}
export default function Home() {
  const [data,setData] = useState<Datatype>();
  const [axiosData,setAxiosData] = useState<Datatype>();
  useEffect(() => {
  
  //USING FETCH
  const dataFetch = async () => {
    try{
      const response =  await fetch("http://www.boredapi.com/api/activity/")

      //I have to check the response to thrown an error when http response is 404
      if (!response.ok) {
        const message = `An error has occured: ${response.status}`;
        throw new Error(message);
      }
  
      const data = await response.json()
       // set state when the data received
      setData(data);
    }
    catch (error: any){
      const message = `An error has occured: ${error.message}`;
      throw new Error(message);
    }
   

  };
  dataFetch();

  // USING AXIOS
  const dataAxios= async () => {
    try {
      const response = await axios.get('http://www.boredapi.com/api/activity/');
      setAxiosData(response.data);
    } catch (error) {
      const err = error as AxiosError
      const message = `An error has occured: ${err.message}`;
      throw new Error(message);
    }
  }

  dataAxios()
},[]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>
            <h1>Activity data fetched with fetch</h1>
            <p>{data ? data.activity : ""}</p>
            <p><b>Type:</b> {data ? data.type : ""}</p>
          </div>
          <div>
            <h1>Activity data fetched with axios</h1>
            <p>{axiosData ? axiosData.activity : ""}</p>
            <p><b>Type:</b> {axiosData ? axiosData.type : ""}</p>
          </div>
        </div>
     
      </main>
    </>
  )
}
